import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import bcrypt from 'bcryptjs';import sharp from 'sharp';import {PGlite} from '@electric-sql/pglite';
import {localDatabase} from '../server/local-db.mjs';import {handle,authorizePage} from '../server/api.mjs';import {seed} from '../server/seed.mjs';import {locations} from '../server/shipping.mjs';import {postgresDatabase} from '../server/postgres.mjs';
const geo=locations(),province=geo.provinces.find(p=>p.name==='Pampanga'),city=geo.cities.find(c=>c.province===province.code&&c.name==='Lubao'),barangay=geo.barangays.find(b=>b.city===city.code),initial='Fixture-Initial-42',password='Fixture-New-Secret-73';
for(const driver of ['sqlite-preview','postgresql'])test('Customer, admin, and security integration: '+driver,async t=>{
 let pg;const DB=driver==='sqlite-preview'?localDatabase(':memory:'):await(async()=>{pg=new PGlite();await pg.exec(fs.readFileSync('prisma/migrations/202610040001_initial/migration.sql','utf8'));const executor=tx=>({$queryRawUnsafe:async(sql,...args)=>(await tx.query(sql,args)).rows,$executeRawUnsafe:async(sql,...args)=>(await tx.query(sql,args)).affectedRows||0});return postgresDatabase({...executor(pg),$transaction:cb=>pg.transaction(tx=>cb(executor(tx)))})})();
 const files=new Map(),env={DB,BUCKET:{put:async(k,b)=>files.set(k,b),get:async k=>files.has(k)?{body:files.get(k)}:null},APP_ORIGIN:'https://bel.test'};await seed({...env,ADMIN_SEED_HASH:await bcrypt.hash(initial,12)});await DB.prepare('INSERT INTO shipping_rates (name,province,city,rate,active,cod_allowed) VALUES (?,?,?,?,1,1)').bind('Test local rate','Pampanga','Lubao',3000).run();let cookie='',csrf='',order,token;
 async function request(path,method='GET',body,admin=false,extra={}){const headers={origin:env.APP_ORIGIN,'Content-Type':'application/json',...(admin?{cookie,'x-csrf-token':csrf}:{}),...extra};if(body instanceof FormData)delete headers['Content-Type'];const r=await handle(new Request(env.APP_ORIGIN+'/api'+path,{method,headers,...(body===undefined?{}:{body:body instanceof FormData?body:JSON.stringify(body)})}),env);return{status:r.status,headers:r.headers,data:(r.headers.get('Content-Type')||'').includes('json')?await r.json():await r.arrayBuffer()}}
 const checkout=(extra={})=>({name:'Test Customer',mobile:'09123456789',email:'test@example.com',address:'Test street',barangay:barangay.name,barangay_code:barangay.code,city:'Lubao',city_code:city.code,province:'Pampanga',province_code:province.code,postal:'2005',payment:'cod',delivery_method:'delivery',items:[{id:1,quantity:2}],idempotency_key:crypto.randomUUID(),tracking_token:crypto.randomUUID()+crypto.randomUUID(),...extra});
 const orderID=async n=>(await DB.prepare('SELECT id FROM orders WHERE number=?').bind(n).first()).id;
 await t.test('public prices and five testimonials, no private data; admin pages/APIs protected',async()=>{const r=await request('/store');assert.equal(r.status,200);assert.deepEqual(r.data.products.map(p=>p.price),[65,125]);assert.equal(r.data.settings.testimonials.length,5);assert.ok(!JSON.stringify(r.data).includes('password_hash'));assert.equal((await request('/admin/overview')).status,401);assert.equal(await authorizePage(new Request(env.APP_ORIGIN+'/admin/dashboard'),env),false)});
 await t.test('generic login, secure cookies, mandatory change, CSRF, complexity, session rotation',async()=>{let r=await request('/admin/login','POST',{username:"' OR 1=1 --",password:'wrong'});const wrong=await request('/admin/login','POST',{username:'bel',password:'wrong'});assert.equal(r.status,401);assert.equal(r.data.error,wrong.data.error);r=await request('/admin/login','POST',{username:'bel',password:initial});assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];csrf=r.data.csrf;assert.match(r.headers.get('set-cookie'),/HttpOnly; SameSite=Strict; Max-Age=28800; Secure/);assert.equal(r.data.must_change,true);assert.equal((await request('/admin/overview','GET',undefined,true)).status,428);assert.equal((await request('/admin/password','POST',{current:initial,password},true,{'x-csrf-token':'bad'})).status,403);assert.equal((await request('/admin/password','POST',{current:initial,password:'weakpassword'},true)).status,400);const old=cookie;r=await request('/admin/password','POST',{current:initial,password},true);assert.equal(r.status,200);cookie=r.headers.get('set-cookie').split(';')[0];csrf=r.data.csrf;assert.notEqual(cookie,old);assert.equal((await request('/admin/overview','GET',undefined,true,{cookie:old})).status,401);assert.equal((await request('/admin/overview','GET',undefined,true)).status,200)});
 await t.test('quantities, disabled payment, address, origin and csrf validated',async()=>{for(const qty of [-1,0,1.5,'1',1001])assert.equal((await request('/orders','POST',checkout({items:[{id:1,quantity:qty}]}))).status,400);assert.equal((await request('/orders','POST',checkout({items:[{id:1,quantity:21}]}))).status,409);assert.equal((await request('/orders','POST',checkout({payment:'gcash'}))).status,400);assert.equal((await request('/orders','POST',checkout({mobile:'123'}))).status,400);assert.equal((await request('/orders','POST',checkout({barangay_code:'not-a-code'}))).status,400);assert.equal((await request('/orders','POST',checkout(),false,{origin:'https://evil.test'})).status,403);assert.equal((await request('/admin/settings','PUT',{},true,{'x-csrf-token':'wrong'})).status,403)});
 await t.test('server totals ignore tampering; idempotency and private tickets',async()=>{const b=checkout({total:1,delivery_fee:-100,price:0});token=b.tracking_token;const r=await request('/orders','POST',b);assert.equal(r.status,201,JSON.stringify(r.data));order={...r.data.order,id:await orderID(r.data.order.number)};assert.equal(order.total,16000);assert.equal(order.status,'Pending Confirmation');assert.equal((await request('/store')).data.products[0].stock,18);assert.equal((await request('/orders','POST',b)).status,200);assert.equal((await request('/store')).data.products[0].stock,18);assert.equal((await request('/orders','POST',{...b,tracking_token:crypto.randomUUID()+crypto.randomUUID()})).status,409);const ticket=await request('/ticket','POST',{number:order.number,token});assert.equal(ticket.status,200);assert.equal(ticket.data.order.address,'Test street');assert.equal((await request('/ticket','POST',{number:order.number,token:'guessed'})).status,404);assert.equal((await request('/ticket','POST',{number:order.number,mobile:'09123456789'})).status,400)});
 await t.test('tracking omits sensitive fields and denies wrong mobile',async()=>{assert.equal((await request('/track','POST',{number:order.number,mobile:'09999999999'})).status,404);const r=await request('/track','POST',{number:order.number,mobile:'09123456789'});assert.equal(r.status,200);for(const k of ['address','mobile','email','tracking_hash','proof_id','customer_id','id','notes','province','city'])assert.equal(r.data.order[k],undefined);assert.equal(r.data.order.name,'Test')});
 await t.test('price precision and injection checks; snapshots preserve old price',async()=>{const p=(await request('/admin/products/1','GET',undefined,true)).data;for(const price of [-1,0.001,Infinity,'0'])assert.equal((await request('/admin/products/1','PUT',{...p,price},true)).status,400);assert.equal((await request('/admin/products/1','PUT',{...p,price:70,description:"Homemade ' ; DROP TABLE orders; --"},true)).status,200);assert.equal((await request('/store')).data.products[0].price,70);assert.equal((await request('/admin/orders/'+order.id,'GET',undefined,true)).data.items[0].unit_price,6500)});
 await t.test('city/province/region/island/default priority; hiding, unavailable location, COD zone restriction',async()=>{const add=async b=>assert.equal((await request('/admin/shipping','POST',{name:'Test rule',rate:100,active:true,cod_allowed:true,...b},true)).status,200);await add({rate:200});await add({region:'Luzon',rate:150});await add({region:geo.regions.find(r=>r.code===province.region).name,rate:120});await add({province:'Pampanga',rate:80});const quote=()=>request('/shipping-quote','POST',{items:[{id:1,quantity:1}],delivery_method:'delivery',province_code:province.code,city_code:city.code,total:0});assert.equal((await quote()).data.fee,3000);const hide=async id=>{const rule=await DB.prepare('SELECT * FROM shipping_rates WHERE id=?').bind(id).first();await request('/admin/shipping/'+id,'PUT',{...rule,rate:rule.rate/100,active:false},true)};for(const[id,fee]of[[1,8000],[5,12000],[4,15000],[3,20000]]){await hide(id);assert.equal((await quote()).data.fee,fee)}await hide(2);assert.equal((await quote()).status,400);const rule={name:'Test local',province:'Pampanga',city:'Lubao',rate:30,active:true};await request('/admin/shipping/1','PUT',{...rule,cod_allowed:false},true);assert.equal((await request('/orders','POST',checkout())).status,400);await request('/admin/shipping/1','PUT',{...rule,cod_allowed:true},true);assert.equal((await request('/admin/shipping','POST',{name:'Invalid',rate:-1,active:true},true)).status,400)});
 await t.test('cancellation restores stock once and statuses are final',async()=>{const path='/admin/orders/'+order.id;assert.equal((await request(path,'PUT',{status:'Cancelled',payment_status:'Unpaid'},true)).status,200);await request(path,'PUT',{status:'Cancelled',payment_status:'Unpaid'},true);assert.equal((await request('/store')).data.products[0].stock,20);assert.equal((await request(path,'PUT',{status:'Confirmed'},true)).status,400)});
 await t.test('GCash needs no upload; manual verification gates courier shipment',async()=>{assert.equal((await request('/admin/settings','PUT',{gcash_enabled:true},true)).status,200);assert.equal((await request('/admin/settings','PUT',{gcash_enabled:true,gcash_name:'Test Account',gcash_number:'09123456789'},true)).status,200);const r=await request('/orders','POST',checkout({payment:'gcash',delivery_method:'delivery'}));assert.equal(r.status,201,JSON.stringify(r.data));const path='/admin/orders/'+await orderID(r.data.order.number);assert.equal(r.data.order.status,'Awaiting Payment Verification');assert.equal((await request(path,'PUT',{status:'Shipped',payment_status:'Pending Verification',courier:'LBC',tracking_number:'TEST12345'},true)).status,400);assert.equal((await request(path,'PUT',{status:'Shipped',payment_status:'Verified'},true)).status,400);assert.equal((await request(path,'PUT',{status:'Shipped',payment_status:'Verified',courier:'LBC',tracking_number:'TEST12345'},true)).status,200);assert.equal((await request('/track','POST',{number:r.data.order.number,mobile:'09123456789'})).data.order.tracking_number,'TEST12345')});
 await t.test('image upload is admin only and rejects invalid signatures, extensions, corrupt and oversized bytes',async()=>{const bytes=await sharp({create:{width:2,height:2,channels:4,background:'#ff0000'}}).png().toBuffer();const form=(data=bytes,name='jar.png',type='image/png')=>{const f=new FormData();f.set('file',new File([data],name,{type}));return f};assert.equal((await request('/upload','POST',form())).status,401);assert.equal((await request('/upload','POST',form(),true,{'x-csrf-token':'bad'})).status,403);for(const[data,name,type]of[[Buffer.from('<svg/>'),'image.png','image/png'],[Buffer.from('<script/>'),'x.svg','image/svg+xml'],[Buffer.from('broken'),'x.jpg','image/jpeg'],[bytes,'x.html','image/png'],[Buffer.alloc(4*1024*1024+1),'large.png','image/png']])assert.equal((await request('/upload','POST',form(data,name,type),true)).status,400);const r=await request('/upload','POST',form(),true);assert.equal(r.status,201,JSON.stringify(r.data));assert.match(r.data.url,/^\/api\/media\/[a-f0-9-]{36}$/);assert.equal((await request('/media/'+r.data.id)).status,200)});
 await t.test('QR-only GCash, prepaid distant deliveries, and manual Lalamove',async()=>{
 await DB.prepare('DELETE FROM rate_limits').run();
 assert.equal((await request('/admin/settings','PUT',{gcash_enabled:true,gcash_name:'',gcash_number:'',gcash_show_number:false,gcash_qr:'/assets/brand.png',lalamove_enabled:true},true)).status,200);
 await DB.prepare('UPDATE shipping_rates SET cod_allowed=0 WHERE province=? AND city=?').bind('Pampanga','Lubao').run();
 assert.equal((await request('/orders','POST',checkout({payment:'cod'}))).status,400);
 const q=await request('/shipping-quote','POST',checkout({delivery_service:'lalamove'}));assert.equal(q.status,200);assert.equal(q.data.separate_fee,true);assert.equal(q.data.cod_allowed,false);
 assert.equal((await request('/orders','POST',checkout({payment:'cod',delivery_service:'lalamove'}))).status,400);
 const r=await request('/orders','POST',checkout({payment:'gcash',delivery_service:'lalamove',items:[{id:1,quantity:1}]}));assert.equal(r.status,201,JSON.stringify(r.data));assert.equal(r.data.order.courier,'Lalamove');assert.equal(r.data.order.total,r.data.order.subtotal);assert.equal(r.data.order.status,'Awaiting Payment Verification');
 const path='/admin/orders/'+await orderID(r.data.order.number);assert.equal((await request(path,'PUT',{status:'Out for Delivery',payment_status:'Pending Verification'},true)).status,400);assert.equal((await request(path,'PUT',{status:'Out for Delivery',payment_status:'Verified',courier:'Lalamove'},true)).status,200);assert.equal((await request(path,'PUT',{status:'Cancelled'},true)).status,200);
 const pickup=await request('/orders','POST',checkout({payment:'gcash',delivery_method:'pickup',delivery_service:'lalamove',items:[{id:1,quantity:1}]}));assert.equal(pickup.status,201);assert.equal(pickup.data.order.courier,'');assert.equal((await request('/admin/orders/'+await orderID(pickup.data.order.number),'PUT',{status:'Cancelled'},true)).status,200);
 await DB.prepare('UPDATE shipping_rates SET cod_allowed=1 WHERE province=? AND city=?').bind('Pampanga','Lubao').run();assert.equal((await request('/shipping-quote','POST',checkout())).data.cod_allowed,true);
 assert.equal((await request('/admin/settings','PUT',{lalamove_enabled:false},true)).status,200);assert.equal((await request('/shipping-quote','POST',checkout({delivery_service:'lalamove'}))).status,400);assert.equal((await request('/admin/settings','PUT',{lalamove_enabled:true},true)).status,200);
 });
 await t.test('testimonials can be sorted, edited, hidden and removed',async()=>{const reviews=[{id:'b',name:'Jo',text:'Second',visible:true,sort:2},{id:'a',name:'Aris',text:'First',visible:true,sort:0},{id:'hidden',name:'Hidden',text:'Do not publish',visible:false,sort:1}];assert.equal((await request('/admin/settings','PUT',{testimonials:reviews},true)).status,200);assert.deepEqual((await request('/store')).data.settings.testimonials.map(t=>t.text),['First','Second']);reviews[0].text='Updated';await request('/admin/settings','PUT',{testimonials:reviews.slice(0,1)},true);assert.deepEqual((await request('/store')).data.settings.testimonials.map(t=>t.text),['Updated'])});
 await t.test('simultaneous last-jar orders cannot oversell or leave orphan customers',async()=>{await DB.prepare('DELETE FROM rate_limits').run();await DB.prepare('UPDATE products SET stock=1 WHERE id=2').run();const before=Number((await DB.prepare('SELECT COUNT(*) AS n FROM orders').first()).n);const results=await Promise.all([request('/orders','POST',checkout({items:[{id:2,quantity:1}],delivery_method:'pickup'})),request('/orders','POST',checkout({items:[{id:2,quantity:1}],delivery_method:'pickup'}))]);assert.deepEqual(results.map(r=>r.status).sort(),[201,409]);assert.equal((await DB.prepare('SELECT stock FROM products WHERE id=2').first()).stock,0);assert.equal(Number((await DB.prepare('SELECT COUNT(*) AS n FROM orders').first()).n),before+1);assert.equal(Number((await DB.prepare('SELECT COUNT(*) AS n FROM customers').first()).n),before+1)});
 await t.test('form honeypots, persisted inquiries/messages and safe audit history',async()=>{const b={name:'Test Person',email:'test@example.com',mobile:'09123456789',subject:'Delivery',message:'Question',location:'Lubao, Pampanga',facebook:'https://www.facebook.com/test'};assert.equal((await request('/contact','POST',{...b,website:'spam'})).status,400);assert.equal((await request('/reseller','POST',{...b,website:'spam'})).status,400);assert.equal((await request('/reseller','POST',{...b,facebook:'https://evil.test/profile'})).status,400);assert.equal((await request('/contact','POST',b)).status,201);assert.equal((await request('/reseller','POST',b)).status,201);const r=await request('/admin/overview','GET',undefined,true);assert.equal(r.data.resellers.length,1);assert.equal(r.data.messages.length,1);for(const action of ['ADMIN_PASSWORD_CHANGED','ORDER_STATUS_UPDATED','STORE_SETTINGS_UPDATED'])assert.ok(r.data.audit.some(a=>a.action===action));assert.ok(!JSON.stringify(r.data.audit).includes(password))});
 await t.test('product creation, gallery, stock corrections, inactivity and soft deletion work on both databases',async()=>{const p={name:'Fixture Jar',slug:'fixture-jar',sku:'FIXTURE-300',size:'300g',price:180,stock:2,description:'Fixture description',short_description:'Fixture copy',image:'/assets/jar-200-cutout.webp',images:['/assets/jar-100-cutout.webp'],active:true,featured:false};const r=await request('/admin/products','POST',p,true);assert.equal(r.status,201,JSON.stringify(r.data));const id=r.data.id;assert.ok(id>2);const detail=(await request('/admin/products/'+id,'GET',undefined,true)).data;assert.equal(detail.images.length,1);assert.equal((await request('/admin/inventory','POST',{id,mode:'add',quantity:5,reason:'Fixture new batch'},true)).status,200);assert.equal((await request('/admin/inventory','POST',{id,mode:'remove',quantity:50,reason:'Invalid removal'},true)).status,400);assert.equal((await request('/admin/inventory','POST',{id,mode:'set',quantity:3,previous:7,reason:'Fixture count'},true)).status,200);assert.equal((await request('/admin/inventory','POST',{id,mode:'set',quantity:1,previous:7,reason:'Stale count'},true)).status,409);assert.equal((await request('/admin/products/'+id,'PUT',{...detail,stock:3,price:185,active:false},true)).status,200);assert.equal((await request('/orders','POST',checkout({items:[{id,quantity:1}],delivery_method:'pickup'}))).status,409);assert.equal((await request('/admin/products/'+id,'DELETE',undefined,true)).status,200);assert.equal((await request('/admin/products/'+id,'GET',undefined,true)).status,404);assert.ok(!(await request('/store')).data.products.some(p=>p.id===id))});
 await t.test('expired session rejected; stored passwords use bcrypt and old password is unusable',async()=>{const r=await request('/admin/login','POST',{username:'bel',password});assert.equal(r.status,200);await DB.prepare('UPDATE sessions SET expires=? WHERE csrf=?').bind(Date.now()-1,r.data.csrf).run();assert.equal((await request('/admin/overview','GET',undefined,true,{cookie:r.headers.get('set-cookie').split(';')[0]})).status,401);assert.equal((await request('/admin/overview','GET',undefined,true)).status,200);const a=await DB.prepare('SELECT password_hash FROM admins WHERE id=1').first();assert.match(a.password_hash,/^\$2[aby]\$12\$/);assert.equal(await bcrypt.compare(initial,a.password_hash),false);assert.equal(await bcrypt.compare(password,a.password_hash),true)});
 await t.test('database errors produce friendly responses without SQL or stack traces',async()=>{const r=await handle(new Request(env.APP_ORIGIN+'/api/store'),{...env,DB:{prepare:()=>{throw Error('SECRET-URL SQL SELECT password_hash')}}});assert.equal(r.status,500);const b=await r.json();assert.ok(!JSON.stringify(b).includes('SECRET-URL'));assert.ok(!JSON.stringify(b).includes('SELECT'));assert.ok(!JSON.stringify(b).includes('stack'))});
 await t.test('method restrictions, logout revocation and login rate limiting',async()=>{assert.equal((await request('/store','POST',{})).status,405);assert.equal((await request('/admin/session','DELETE',{})).status,405);assert.equal((await request('/admin/logout','POST',{},true)).status,200);assert.equal((await request('/admin/overview','GET',undefined,true)).status,401);let r;for(let i=0;i<22;i++)r=await request('/admin/login','POST',{username:'bel',password:'wrong'});assert.equal(r.status,429)});
 if(pg)await pg.close();else DB.close();
});

// Browser origin must match the public preview, even when Next uses an internal host.
import {appOrigin} from '../server/environment.mjs';
test('preview origin is explicit and production requires configuration',()=>{assert.equal(appOrigin({NODE_ENV:'development'}),'http://127.0.0.1:5173');assert.equal(appOrigin({NODE_ENV:'development',PORT:'5175'}),'http://127.0.0.1:5175');assert.equal(appOrigin({NODE_ENV:'production'}),undefined);assert.equal(appOrigin({NODE_ENV:'production',APP_ORIGIN:'https://bel.test'}),'https://bel.test')});

test('Next internal localhost URL accepts configured browser origin and rejects external origins',async()=>{
 const db=localDatabase(':memory:');await seed({DB:db});const env={DB:db,APP_ORIGIN:appOrigin({NODE_ENV:'development',PORT:'5173'})};
 const call=(origin,site='same-origin')=>handle(new Request('http://localhost:5173/api/shipping-quote',{method:'POST',headers:{origin,'sec-fetch-site':site,'content-type':'application/json'},body:JSON.stringify({delivery_method:'pickup',items:[{id:1,quantity:1}]})}),env);
 assert.equal((await call('http://127.0.0.1:5173')).status,200);assert.equal((await call('https://evil.test')).status,403);assert.equal((await call('http://127.0.0.1:5173','cross-site')).status,403);db.close();
});
