import bcrypt from 'bcryptjs';
import sharp from 'sharp';
import {defaults} from './seed.mjs';
import {quote,locations} from './shipping.mjs';
import {extras} from './extras.mjs';
const statuses=['Pending Confirmation','Awaiting Payment Verification','Payment Rejected','Payment Verified','Confirmed','Preparing Order','Shipped','Ready for Pickup','Out for Delivery','Completed','Cancelled'];
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...headers}});
class HttpError extends Error{constructor(message,status=400){super(message);this.status=status;}}
const fail=(message,status)=>{throw new HttpError(message,status)};
const clean=(v,max=500)=>typeof v==='string'?v.trim().replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').slice(0,max):'';
const required=(v,name,max=500)=>{const x=clean(v,max);if(!x)fail(name+' is required.');return x};
const integer=(v,name,min=0,max=1000000)=>{if(typeof v!=='number'||!Number.isSafeInteger(v)||v<min||v>max)fail(name+' is invalid.');return v};
const money=(v,name)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1000000)fail(name+' must be a valid non-negative amount.');if(Math.abs(v*100-Math.round(v*100))>0.00001)fail(name+' must have at most two decimal places.');return Math.round(v*100)};
const mobile=v=>{const x=clean(v).replace(/[\s()-]/g,'').replace(/^\+63/,'0');if(!/^09\d{9}$/.test(x))fail('Enter a valid Philippine mobile number (09XXXXXXXXX).');return x};
const email=v=>{const x=clean(v,200);if(x&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x))fail('Enter a valid email address.');return x};
const uuid=()=>crypto.randomUUID();
const sha=async v=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const token=()=>uuid()+uuid();
const parse=async req=>{if(!(req.headers.get('content-type')||'').includes('application/json'))fail('JSON required.',415);const b=await req.text();if(b.length>100000)fail('Request too large.',413);try{const value=JSON.parse(b);if(!value||typeof value!=='object'||Array.isArray(value))fail('Invalid request.');return value}catch{fail('Invalid request.')}};
const one=(db,sql,...args)=>db.prepare(sql).bind(...args).first();
const all=async(db,sql,...args)=>(await db.prepare(sql).bind(...args).all()).results;
const run=(db,sql,...args)=>db.prepare(sql).bind(...args).run();
export async function settings(db){return Object.fromEntries((await all(db,'SELECT key,value FROM store_settings')).map(r=>[r.key,JSON.parse(r.value)]))}
const cookie=(value,secure,age=28800)=>`bel_session=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}${secure?'; Secure':''}`;
async function session(req,db){const t=(req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('bel_session='))?.slice(12);if(!t)return null;return one(db,'SELECT s.*,a.username,a.must_change FROM sessions s JOIN admins a ON a.id=s.admin_id WHERE s.token_hash=? AND s.expires>?',await sha(t),Date.now())}
async function limit(req,db,bucket,max){const ip=req.headers.get('x-vercel-forwarded-for')?.split(',')[0]||'local';const window=Math.floor(Date.now()/600000);const key=await sha(ip+':'+bucket+':'+window);await run(db,'INSERT INTO rate_limits (key,count,expires) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1',key,Date.now()+600000);const r=await one(db,'SELECT count FROM rate_limits WHERE key=?',key);if(r.count>max)fail('Too many attempts. Please try again in 10 minutes.',429);await run(db,'DELETE FROM rate_limits WHERE expires<?',Date.now()-600000)}
function productData(b){const slug=required(b.slug,'Slug',100);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))fail('Use lowercase words separated by hyphens for the slug.');const image=required(b.image,'Product image',200);if(!/^\/(assets\/[a-zA-Z0-9._-]+|api\/media\/[a-f0-9-]+)$/.test(image))fail('Upload a product image first.');return {name:required(b.name,'Product name',150),slug,size:required(b.size,'Size',50),price:money(b.price,'Price'),stock:integer(b.stock,'Stock'),description:required(b.description,'Description',5000),short_description:required(b.short_description,'Short description',300),image,sku:required(b.sku,'SKU',80),active:b.active?1:0,featured:b.featured?1:0}}
async function orderView(db,id,admin=false){const o=await one(db,'SELECT o.*,c.name,c.mobile,c.email,p.method AS payment_method,p.status AS payment_status,p.proof_id,p.reason AS payment_reason FROM orders o JOIN customers c ON c.id=o.customer_id JOIN payments p ON p.order_id=o.id WHERE o.id=?',id);if(!o)return null;o.items=await all(db,'SELECT name,size,image,unit_price,quantity,product_id FROM order_items WHERE order_id=?',id);delete o.tracking_hash;delete o.idempotency_key;if(!admin){o.name=o.name.split(' ')[0];delete o.customer_id;delete o.proof_id;delete o.email;delete o.address;delete o.barangay;delete o.city;delete o.province;delete o.postal;delete o.mobile;delete o.notes;delete o.region;delete o.shipping_zone;delete o.id}return o}
async function audit(db,s,action,entity_type,entity_id,metadata={}){await run(db,'INSERT INTO audit_logs (admin_id,action,entity_type,entity_id,metadata) VALUES (?,?,?,?,?)',s?.admin_id||null,action,entity_type,String(entity_id||''),JSON.stringify(metadata));}
const auditAction=path=>path.includes('password')?'ADMIN_PASSWORD_CHANGED':path.includes('orders')?'ORDER_STATUS_UPDATED':path.includes('products')?'PRODUCT_UPDATED':path.includes('inventory')?'INVENTORY_UPDATED':path.includes('settings')?'STORE_SETTINGS_UPDATED':path.includes('logout')?'ADMIN_LOGOUT':'ADMIN_ACTION';
async function handleRequest(req,env){const url=new URL(req.url);const path=url.pathname;const db=env.DB;
 try{if(!db)fail('The store database is unavailable. Please try again shortly.',503);
 const mutation=!['GET','HEAD','OPTIONS'].includes(req.method);if(mutation){const origin=req.headers.get('origin');const allowed=env.APP_ORIGIN||url.origin;if(!origin||origin!==allowed||req.headers.get('sec-fetch-site')==='cross-site')fail('This request must come from the store website.',403);const size=Number(req.headers.get('content-length'));if(size>6*1024*1024)fail('Request too large.',413)}
 const s=await session(req,db);const adminRoute=path.startsWith('/api/admin/')&&!['/api/admin/login','/api/admin/session'].includes(path);
 if(adminRoute){if(!s)fail('Please sign in to continue.',401);if(mutation&&req.headers.get('x-csrf-token')!==s.csrf)fail('Session validation failed. Refresh and try again.',403);if(s.must_change&&!['/api/admin/password','/api/admin/logout'].includes(path))fail('Change your initial password to continue.',428)}
 const extra=await extras({path,req,db,s,parse,fail,required,clean,money,mobile,email,all,one,run,json,settings,limit,audit:(session,action,type,id,meta)=>audit(db,session,action,type,id,meta)});if(extra)return extra;
 if(path==='/api/store'&&req.method==='GET'){const products=await all(db,'SELECT * FROM products WHERE active=1 AND deleted=0 ORDER BY id');const images=await all(db,'SELECT * FROM product_images');return json({settings:publicSettings(await settings(db)),products:products.map(p=>({...p,price:p.price/100,images:images.filter(i=>i.product_id===p.id).map(i=>i.url)}))})}
 if(path==='/api/admin/session'&&req.method==='GET')return json(s?{username:s.username,csrf:s.csrf,must_change:!!s.must_change}:{username:null});
 if(path==='/api/admin/login'&&req.method==='POST'){await limit(req,db,'login',10);const b=await parse(req);const a=await one(db,'SELECT * FROM admins WHERE username=?',clean(b.username,100));const valid=typeof b.password==='string'&&b.password.length<=72&&await bcrypt.compare(b.password,a?.password_hash||await dummyHash)&&!!a;if(!valid){await audit(db,null,'ADMIN_LOGIN_FAILED','admin','');fail('Incorrect username or password.',401);}await audit(db,{admin_id:a.id},'ADMIN_LOGIN_SUCCESS','admin',a.id);const t=token(),csrf=token();await run(db,'INSERT INTO sessions (token_hash,admin_id,csrf,expires) VALUES (?,?,?,?)',await sha(t),a.id,csrf,Date.now()+28800000);await run(db,'DELETE FROM sessions WHERE expires<?',Date.now());return json({username:a.username,csrf,must_change:!!a.must_change},200,{'Set-Cookie':cookie(t,url.protocol==='https:')})}
 if(path==='/api/admin/logout'&&req.method==='POST'){await run(db,'DELETE FROM sessions WHERE token_hash=?',s.token_hash);return json({ok:true},200,{'Set-Cookie':cookie('',url.protocol==='https:',0)})}
 if(path==='/api/admin/password'&&req.method==='POST'){const b=await parse(req);const a=await one(db,'SELECT * FROM admins WHERE id=?',s.admin_id);if(typeof b.current!=='string'||!await bcrypt.compare(b.current,a.password_hash))fail('Current password is incorrect.');if(typeof b.password!=='string'||b.password.length<12||b.password.length>72||!/[A-Z]/.test(b.password)||!/[a-z]/.test(b.password)||!/[0-9]/.test(b.password))fail('Use 12–72 characters with an uppercase letter, lowercase letter, and number.');if(await bcrypt.compare(b.password,a.password_hash))fail('Choose a different password.');await db.batch([db.prepare('UPDATE admins SET password_hash=?,must_change=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(await bcrypt.hash(b.password,12),s.admin_id),db.prepare('DELETE FROM sessions WHERE admin_id=?').bind(s.admin_id)]);const t=token(),nextCsrf=token();await run(db,'INSERT INTO sessions (token_hash,admin_id,csrf,expires) VALUES (?,?,?,?)',await sha(t),s.admin_id,nextCsrf,Date.now()+28800000);await audit(db,s,'ADMIN_PASSWORD_CHANGED','admin',s.admin_id);return json({ok:true,csrf:nextCsrf},200,{'Set-Cookie':cookie(t,url.protocol==='https:')})}
 if(path==='/api/upload'&&req.method==='POST'){await limit(req,db,'uploads',30);if(!s)fail('Administrator access required.',401);if(s.must_change||req.headers.get('x-csrf-token')!==s.csrf)fail('Administrator access required.',403);const bytes=await req.arrayBuffer();if(bytes.byteLength>6*1024*1024)fail('Maximum upload size is 4 MB.',413);const form=await new Request(req.url,{method:'POST',headers:{'content-type':req.headers.get('content-type')||''},body:bytes}).formData();const file=form.get('file');const kind='product';if(!s)fail('Administrator access required.',401);if(s.must_change||req.headers.get('x-csrf-token')!==s.csrf)fail('Administrator access required.',403);if(!file||typeof file.arrayBuffer!=='function'||!file.size||file.size>4*1024*1024)fail('Choose an image smaller than 4 MB.');const b=new Uint8Array(await file.arrayBuffer());let mime='';if(b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71&&b[4]===13&&b[5]===10&&b[6]===26&&b[7]===10)mime='image/png';else if(b[0]===255&&b[1]===216&&b[2]===255)mime='image/jpeg';else if(new TextDecoder().decode(b.slice(0,4))==='RIFF'&&new TextDecoder().decode(b.slice(8,12))==='WEBP')mime='image/webp';if(!mime||!validImage(b,mime)||file.type!==mime||! /\.(png|jpe?g|webp)$/i.test(file.name))fail('Only valid JPG, PNG, and WEBP images are accepted.');try{await sharp(b,{limitInputPixels:40000000,animated:false}).stats()}catch{fail('The image is damaged or unsupported.');}if(!env.BUCKET)fail('Image storage is unavailable.',503);const id=uuid(),claim=token();await env.BUCKET.put(id,b,{httpMetadata:{contentType:mime}});await run(db,'INSERT INTO uploads (id,kind,mime,size,claim_hash) VALUES (?,?,?,?,?)',id,kind,mime,file.size,await sha(claim));return json({id,claim,url:'/api/media/'+id},201)}
 if(path.startsWith('/api/media/')&&req.method==='GET'){const id=path.split('/').pop();const f=await one(db,'SELECT * FROM uploads WHERE id=?',id);if(!f)fail('Image not found.',404);if(f.kind==='proof'&&(!s||s.must_change))fail('Administrator access required.',403);const object=await env.BUCKET.get(id);if(!object)fail('Image not found.',404);return new Response(object.body,{headers:{'Content-Type':f.mime,'X-Content-Type-Options':'nosniff','Cache-Control':f.kind==='proof'?'private, no-store':'public, max-age=3600'}})}
 if(path==='/api/orders'&&req.method==='POST'){await limit(req,db,'orders',15);const b=await parse(req);const idempotency=required(b.idempotency_key,'Checkout reference',100);if(!/^[a-f0-9-]{36}$/.test(idempotency))fail('Invalid checkout reference.');const tracking=required(b.tracking_token,'Tracking token',100);if(!/^[a-f0-9-]{72}$/.test(tracking))fail('Invalid tracking token.');const exists=await one(db,'SELECT id,tracking_hash FROM orders WHERE idempotency_key=?',idempotency);if(exists){if(exists.tracking_hash!==await sha(tracking))fail('This checkout reference has already been used.',409);return json({order:await orderView(db,exists.id),tracking_token:tracking})}
 const st=await settings(db);const customer={id:uuid(),name:required(b.name,'Full name',120),mobile:mobile(b.mobile),email:email(b.email)};if(!['cod','gcash'].includes(b.payment)||!st[b.payment+'_enabled'])fail('Select an available payment method.');if(b.payment==='gcash'&&!st.gcash_qr&&(!st.gcash_name||!st.gcash_number))fail('GCash has not been configured.');if(!['delivery','pickup'].includes(b.delivery_method)||(b.delivery_method==='pickup'&&!st.pickup_enabled))fail('Select an available delivery option.');const address={};for(const key of ['address','barangay','city','province','postal'])address[key]=b.delivery_method==='delivery'?required(b[key],key==='address'?'Complete address':key,250):clean(b[key],250);if(b.delivery_method==='delivery'&&!/^\d{4}$/.test(address.postal))fail('Use a four-digit postal code.');if(!Array.isArray(b.items)||!b.items.length||b.items.length>50)fail('Your bag is empty.');const ids=new Set();let subtotal=0;const items=[];for(const item of b.items){const id=integer(item.id,'Product',1),qty=integer(item.quantity,'Quantity',1,1000);if(ids.has(id))fail('Duplicate cart item.');ids.add(id);const p=await one(db,'SELECT * FROM products WHERE id=? AND active=1 AND deleted=0',id);if(!p||p.stock<qty)fail('A product is no longer available in the requested quantity.',409);items.push({...p,quantity:qty});subtotal+=p.price*qty;if(subtotal>2000000000)fail('This order exceeds the maximum allowed amount.')}
 let shipping;try{shipping=await quote(db,b,subtotal,st)}catch(e){fail(e.message)}const fee=shipping.fee;if(subtotal+fee>2000000000)fail('This order exceeds the maximum allowed amount.');if(b.payment==='cod'&&!shipping.cod_allowed)fail('Cash on Delivery is unavailable for this shipping zone. Select GCash.');if(shipping.location){Object.assign(address,shipping.location);const list=locations().barangays;const barangay=list.find(x=>x.city===shipping.location.city_code&&(b.barangay_code?x.code===b.barangay_code:x.name.toLowerCase()===address.barangay.toLowerCase()));if(!barangay)fail('Select a valid barangay in your city or municipality.');address.barangay=barangay.name;}const proof=null;
 const number='BEL-'+new Date().getUTCFullYear()+'-'+uuid().slice(0,8).toUpperCase();if(customer.name.length<2)fail('Enter your full name.');const status=b.payment==='gcash'?'Awaiting Payment Verification':'Pending Confirmation';const statements=[db.prepare('INSERT INTO customers (id,name,mobile,email) VALUES (?,?,?,?)').bind(customer.id,customer.name,customer.mobile,customer.email),db.prepare('INSERT INTO orders (number,customer_id,address,barangay,city,province,postal,delivery_method,subtotal,delivery_fee,total,status,notes,tracking_hash,idempotency_key,region,shipping_zone) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(number,customer.id,address.address,address.barangay,address.city,address.province,address.postal,b.delivery_method,subtotal,fee,subtotal+fee,status,clean(b.notes,2000),await sha(tracking),idempotency,shipping.location?.region||'',shipping.name)];if(b.delivery_method==='delivery'&&b.delivery_service==='lalamove')statements.push(db.prepare('UPDATE orders SET courier=? WHERE number=?').bind('Lalamove',number));for(const p of items)statements.push(db.prepare('INSERT INTO order_items (order_id,product_id,name,size,image,unit_price,quantity) VALUES ((SELECT id FROM orders WHERE number=?),?,?,?,?,?,?)').bind(number,p.id,p.name,p.size,p.image,p.price,p.quantity));statements.push(db.prepare('INSERT INTO payments (order_id,method,status,proof_id) VALUES ((SELECT id FROM orders WHERE number=?),?,?,?)').bind(number,b.payment,b.payment==='gcash'?'Pending Verification':'Unpaid',proof?.id||null));if(proof)statements.push(db.prepare('UPDATE uploads SET claimed=1 WHERE id=?').bind(proof.id));try{await db.batch(statements)}catch(e){if(/stock|inactive|constraint|UNIQUE/i.test(e.message))fail('Stock or checkout details changed. Review your bag and try again.',409);throw e}const o=await one(db,'SELECT id FROM orders WHERE number=?',number);return json({order:await orderView(db,o.id),tracking_token:tracking},201)}
 if(path==='/api/track'&&req.method==='POST'){await limit(req,db,'track',30);const b=await parse(req);const number=required(b.number,'Order number',50).toUpperCase();const o=await one(db,'SELECT o.id,o.tracking_hash,c.mobile FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.number=?',number);const match=o&&(b.token?o.tracking_hash===await sha(clean(b.token,100)):o.mobile===mobile(b.mobile));if(!match)fail('No matching order found. Check the order number and mobile number.',404);return json({order:await orderView(db,o.id)})}
 if(path==='/api/ticket'&&req.method==='POST'){await limit(req,db,'ticket',30);const b=await parse(req);const o=await one(db,'SELECT id,tracking_hash FROM orders WHERE number=?',required(b.number,'Order number',50));if(!o||o.tracking_hash!==await sha(required(b.token,'Order access token',100)))fail('Order ticket access denied.',404);const result=await orderView(db,o.id,true);delete result.proof_id;return json({order:result})}
 if(path==='/api/contact'&&req.method==='POST'){await limit(req,db,'contact',8);const b=await parse(req);if(b.website)fail('Unable to accept this submission.');if(required(b.name,'Name',100).length<2)fail('Enter your full name.');await run(db,'INSERT INTO contact_messages (name,email,mobile,subject,message) VALUES (?,?,?,?,?)',required(b.name,'Name',120),email(required(b.email,'Email',200)),mobile(b.mobile),required(b.subject,'Subject',150),required(b.message,'Message',4000));return json({ok:true},201)}
 if(path==='/api/admin/overview'&&req.method==='GET'){const products=await all(db,'SELECT * FROM products WHERE deleted=0 ORDER BY id');const orders=await all(db,'SELECT o.*,c.name,c.mobile,p.method AS payment_method,p.status AS payment_status FROM orders o JOIN customers c ON c.id=o.customer_id JOIN payments p ON p.order_id=o.id ORDER BY o.created_at DESC');const movements=await all(db,'SELECT m.*,p.name,p.size,p.sku FROM inventory_movements m JOIN products p ON p.id=m.product_id ORDER BY m.id DESC LIMIT 200');return json({products:products.map(p=>({...p,price:p.price/100})),orders,movements,shipping:await all(db,'SELECT * FROM shipping_rates ORDER BY id'),resellers:await all(db,'SELECT * FROM reseller_inquiries ORDER BY id DESC LIMIT 200'),audit:await all(db,'SELECT id,admin_id,action,entity_type,entity_id,metadata,created_at FROM audit_logs ORDER BY id DESC LIMIT 200'),settings:await settings(db),messages:await all(db,'SELECT * FROM contact_messages ORDER BY id DESC LIMIT 100'),statuses})}
 if(path==='/api/admin/products'&&req.method==='POST'){const b=await parse(req),p=productData(b);validateImages(b.images);const keys=Object.keys(p);const r=await run(db,`INSERT INTO products (${keys.join(',')}) VALUES (${keys.map(()=>'?').join(',')})`,...Object.values(p));const id=r.meta.last_row_id;await run(db,'INSERT INTO inventory_movements (product_id,delta,reason) VALUES (?,?,?)',id,p.stock,'Initial inventory');await saveImages(db,id,b.images);return json({id},201)}
 const productMatch=path.match(/^\/api\/admin\/products\/(\d+)$/);if(productMatch){const id=Number(productMatch[1]);const old=await one(db,'SELECT * FROM products WHERE id=? AND deleted=0',id);if(!old)fail('Product not found.',404);if(req.method==='GET')return json({...old,price:old.price/100,images:(await all(db,'SELECT url FROM product_images WHERE product_id=?',id)).map(r=>r.url)});if(req.method==='DELETE'){await run(db,'UPDATE products SET deleted=1,active=0,updated_at=CURRENT_TIMESTAMP WHERE id=?',id);return json({ok:true})}if(req.method==='PUT'){const b=await parse(req),p=productData(b);validateImages(b.images);if(p.stock!==old.stock)fail('Use Inventory to change stock. Product quantities may have changed since you opened this form.',409);delete p.stock;await run(db,`UPDATE products SET ${Object.keys(p).map(k=>k+'=?').join(',')},updated_at=CURRENT_TIMESTAMP WHERE id=?`,...Object.values(p),id);await saveImages(db,id,b.images);return json({ok:true})}}
 if(path==='/api/admin/inventory'&&req.method==='POST'){const b=await parse(req);const id=integer(b.id,'Product',1);const p=await one(db,'SELECT stock FROM products WHERE id=? AND deleted=0',id);if(!p)fail('Product not found.',404);const qty=integer(b.quantity,'Quantity');let delta;if(b.mode==='set'){if(integer(b.previous,'Previous stock')!==p.stock)fail('Stock changed. Refresh before correcting it.',409);delta=qty-p.stock}else if(b.mode==='add')delta=qty;else if(b.mode==='remove')delta=-qty;else fail('Choose add, remove, or correct.');if(p.stock+delta<0)fail('Stock cannot be negative.');await db.batch([db.prepare('UPDATE products SET stock=CASE WHEN ?=0 OR stock=? THEN stock+? ELSE -1 END,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.mode==='set'?1:0,p.stock,delta,id),db.prepare('INSERT INTO inventory_movements (product_id,delta,reason) VALUES (?,?,?)').bind(id,delta,required(b.reason,'Reason',300))]);return json({ok:true})}
 const orderMatch=path.match(/^\/api\/admin\/orders\/(\d+)$/);if(orderMatch){const id=Number(orderMatch[1]);const o=await orderView(db,id,true);if(!o)fail('Order not found.',404);if(req.method==='GET')return json(o);if(req.method==='PUT'){const b=await parse(req);if(!statuses.includes(b.status))fail('Invalid order status.');if(['Cancelled','Completed'].includes(o.status)&&b.status!==o.status)fail('Completed and cancelled orders are final.');if(b.status==='Ready for Pickup'&&o.delivery_method!=='pickup')fail('This order is for delivery.');if(b.status==='Out for Delivery'&&o.delivery_method!=='delivery')fail('This order is for pickup.');const paymentStatus=b.payment_status||o.payment_status;const allowed=o.payment_method==='gcash'?['Pending Verification','Verified','Rejected']:['Unpaid','Paid'];if(!allowed.includes(paymentStatus))fail('Invalid payment status.');if(o.payment_method==='gcash'&&['Payment Verified','Confirmed','Preparing Order','Shipped','Ready for Pickup','Out for Delivery','Completed'].includes(b.status)&&paymentStatus!=='Verified')fail('Verify the GCash payment before confirming this order.');if(b.status==='Completed'&&o.payment_method==='cod'&&paymentStatus!=='Paid')fail('Mark the cash payment as paid before completing the order.');const reason=paymentStatus==='Rejected'?clean(b.reason,1000):'';const courier=clean(b.courier||o.courier,50),trackingNumber=clean(b.tracking_number||o.tracking_number,100);if(courier&&!['J&T Express','LBC','Lalamove','BEL Local Delivery'].includes(courier))fail('Select an available courier.');if(trackingNumber&&!/^[a-zA-Z0-9-]{5,100}$/.test(trackingNumber))fail('Enter a valid tracking number.');if(b.status==='Shipped'&&(!courier||(['J&T Express','LBC'].includes(courier)&&!trackingNumber)))fail('Select a courier and enter a tracking number before marking shipped.');await db.batch([db.prepare('UPDATE orders SET status=?,courier=?,tracking_number=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(b.status,courier,trackingNumber,id),db.prepare('UPDATE payments SET status=?,reason=?,updated_at=CURRENT_TIMESTAMP WHERE order_id=?').bind(paymentStatus,reason,id)]);if(paymentStatus!==o.payment_status)await audit(db,s,o.payment_method==='gcash'&&paymentStatus==='Verified'?'GCASH_PAYMENT_VERIFIED':'PAYMENT_STATUS_UPDATED','order',id);return json({ok:true})}}
 if(path==='/api/admin/settings'&&req.method==='PUT'){const b=await parse(req),v={};for(const k of Object.keys(defaults)){if(!(k in b))continue;const d=defaults[k];if(k==='testimonials'){if(!Array.isArray(b[k])||b[k].length>50)fail('Use up to 50 testimonials.');v[k]=b[k].map((t,i)=>({id:clean(t.id,50)||uuid(),name:required(t.name,'Customer name',100),text:required(t.text,'Testimonial',2000),visible:!!t.visible,sort:integer(t.sort??i,'Sort order',0,10000)}));continue;}if(typeof d==='boolean')v[k]=!!b[k];else if(typeof d==='number'){money(b[k],k);v[k]=b[k]}else if(k==='faqs'){if(!Array.isArray(b[k])||b[k].length>25)fail('Use up to 25 FAQs.');v[k]=b[k].map(f=>({q:required(f.q,'FAQ question',300),a:required(f.a,'FAQ answer',2000)}))}else v[k]=clean(b[k],['about','storage'].includes(k)?5000:1000)}if(v.phone)mobile(v.phone);if(v.email)email(v.email);for(const k of ['facebook','instagram','tiktok'])if(v[k]&&!/^https:\/\//.test(v[k]))fail('Social links must start with https://.');for(const k of ['logo','gcash_qr'])if(v[k]&&!/^\/(assets\/[a-zA-Z0-9._-]+|api\/media\/[a-f0-9-]+)$/.test(v[k]))fail('Upload a valid image.');const merged={...await settings(db),...v};if(!merged.business_name||!merged.phone||!merged.address||!merged.hero_title)fail('Business name, phone, address, and hero title are required.');if(merged.gcash_number)mobile(merged.gcash_number);await db.batch(Object.entries(v).map(([k,value])=>db.prepare('UPDATE store_settings SET value=?,updated_at=CURRENT_TIMESTAMP WHERE key=?').bind(JSON.stringify(value),k)));return json({ok:true})}
 if(knownPath(path))fail('Method not allowed.',405);fail('This page could not be found.',404);
 }catch(e){if(!(e instanceof HttpError))console.error('BEL API error',e.code||e.name||'UnknownError');if(/stock_nonnegative/.test(e.message))return json({error:'Stock changed or would become negative. Refresh inventory and try again.'},409);const constraint=/UNIQUE constraint|unique constraint|P2002/.test(e.message);return json({error:constraint?'That slug or SKU is already in use.':e instanceof HttpError?e.message:'Unable to complete this request. Please try again.',code:e.status||500},constraint?409:e.status||500)}}
async function saveImages(db,id,images=[]){if(!Array.isArray(images)||images.length>8)fail('Use up to 8 additional images.');for(const url of images)if(typeof url!=='string'||!/^\/(assets\/[a-zA-Z0-9._-]+|api\/media\/[a-f0-9-]+)$/.test(url))fail('Invalid gallery image.');await db.batch([db.prepare('DELETE FROM product_images WHERE product_id=?').bind(id),...images.map(url=>db.prepare('INSERT INTO product_images (product_id,url) VALUES (?,?)').bind(id,url))])}
export async function authorizePage(req,env){return !!(await session(req,env.DB))}

function validateImages(images=[]){if(!Array.isArray(images)||images.length>8)fail('Use up to 8 additional images.');for(const url of images)if(typeof url!=='string'||!/^\/(assets\/[a-zA-Z0-9._-]+|api\/media\/[a-f0-9-]+)$/.test(url))fail('Invalid gallery image.');}
function validImage(b,mime){const view=new DataView(b.buffer,b.byteOffset,b.byteLength);if(mime==='image/png'){if(b.length<67||view.getUint32(8)!==13||new TextDecoder().decode(b.slice(12,16))!=='IHDR'||new TextDecoder().decode(b.slice(-8,-4))!=='IEND')return false;const w=view.getUint32(16),h=view.getUint32(20);return w>0&&h>0&&w*h<=40000000}if(mime==='image/jpeg')return b.length>100&&b[b.length-2]===255&&b[b.length-1]===217;if(mime==='image/webp')return b.length>=30&&view.getUint32(4,true)+8===b.length&&['VP8 ','VP8L','VP8X'].includes(new TextDecoder().decode(b.slice(12,16)));return false}

function publicSettings(st){return {...st,gcash_number:st.gcash_show_number?st.gcash_number:'',testimonials:(st.testimonials||[]).filter(t=>t.visible).sort((a,b)=>a.sort-b.sort)}}
function knownPath(path){return ['/api/store','/api/admin/session','/api/admin/login','/api/admin/logout','/api/admin/password','/api/upload','/api/orders','/api/track','/api/ticket','/api/contact','/api/admin/overview','/api/admin/products','/api/admin/inventory','/api/admin/settings','/api/shipping-quote','/api/locations','/api/reseller','/api/admin/shipping'].includes(path)||/^\/api\/(media|admin\/(orders|products|shipping|resellers))\/[a-zA-Z0-9-]+$/.test(path)}
export async function pageSession(req,env){return session(req,env.DB)}

const dummyHash=bcrypt.hash(crypto.randomUUID(),12);
export async function handle(req,env){let prior=null;const adminMutation=req.method!=='GET'&&(req.url.includes('/api/admin/')||new URL(req.url).pathname==='/api/upload');if(adminMutation&&env.DB)try{prior=await session(req,env.DB)}catch{}const result=await handleRequest(req,env);const path=new URL(req.url).pathname;if(result.ok&&prior&&adminMutation&&!['/api/admin/login','/api/admin/password'].includes(path)){try{await audit(env.DB,prior,auditAction(path),path.split('/')[3]||'upload',path.split('/').pop())}catch{console.error('BEL audit recording failed');}}return result;}
