import {locations,quote} from './shipping.mjs';
export async function extras({path,req,db,s,parse,fail,required,clean,money,mobile,email,all,one,run,json,settings,limit,audit}){
 if(path==='/api/locations'&&req.method==='GET'){const u=new URL(req.url),d=locations(),level=u.searchParams.get('level');if(level==='regions')return json(d.regions);if(level==='provinces')return json(d.provinces.filter(p=>!u.searchParams.get('region')||p.region===u.searchParams.get('region')));if(level==='cities')return json(d.cities.filter(c=>c.province===u.searchParams.get('province')));if(level==='barangays')return json(d.barangays.filter(c=>c.city===u.searchParams.get('city')));fail('Invalid address lookup.');}
 if(path==='/api/shipping-quote'&&req.method==='POST'){await limit(req,db,'quote',120);const b=await parse(req);let subtotal=0;if(!Array.isArray(b.items)||b.items.length>50)fail('Invalid bag.');for(const i of b.items){if(!Number.isSafeInteger(i.id)||!Number.isSafeInteger(i.quantity)||i.quantity<1||i.quantity>1000)fail('Invalid quantity.');const p=await one(db,'SELECT price FROM products WHERE id=? AND active=1 AND deleted=0',i.id);if(!p)fail('Product unavailable.');subtotal+=p.price*i.quantity}try{return json({...await quote(db,b,subtotal,await settings(db)),subtotal})}catch(e){fail(e.message)}}
 if(path==='/api/reseller'&&req.method==='POST'){await limit(req,db,'reseller',8);const b=await parse(req);if(b.website)fail('Unable to accept this submission.');const name=required(b.name,'Name',100);if(name.length<2)fail('Enter your full name.');const fb=clean(b.facebook,500);if(fb){try{const u=new URL(fb);if(u.protocol!=='https:'||!['facebook.com','www.facebook.com','m.facebook.com'].includes(u.hostname))fail('Use a valid Facebook profile URL.')}catch{fail('Use a valid Facebook profile URL.')}}await run(db,'INSERT INTO reseller_inquiries (name,email,mobile,location,facebook,message) VALUES (?,?,?,?,?,?)',name,email(required(b.email,'Email',200)),mobile(b.mobile),required(b.location,'Location',300),fb,required(b.message,'Message',3000));return json({ok:true},201)}
 if(path==='/api/admin/shipping'&&req.method==='GET')return json(await all(db,'SELECT * FROM shipping_rates ORDER BY id'));
 const match=path.match(/^\/api\/admin\/shipping(?:\/(\d+))?$/);if(match&&['POST','PUT','DELETE'].includes(req.method)){const id=match[1]?Number(match[1]):null;if(id&&!await one(db,'SELECT id FROM shipping_rates WHERE id=?',id))fail('Shipping rule not found.',404);if(req.method==='DELETE'){await run(db,'DELETE FROM shipping_rates WHERE id=?',id);await audit(s,'SHIPPING_RULE_DELETED','shipping',id);return json({ok:true})}const b=await parse(req);const name=required(b.name,'Rule name',120),region=clean(b.region,120),province=clean(b.province,120),city=clean(b.city,120);if(city&&!province)fail('A municipality/city rule must include its province.');const data=locations();if(province&&!data.provinces.some(p=>p.name===province))fail('Select a valid province.');if(city&&!data.cities.some(c=>c.name===city&&data.provinces.find(p=>p.code===c.province)?.name===province))fail('Select a valid municipality or city.');if(region&&!data.regions.some(r=>[r.name,r.group,r.zone].includes(region)))fail('Select a valid region or island group.');const rate=money(b.rate,'Shipping rate');const args=[name,region,province,city,rate,b.active?1:0,b.cod_allowed?1:0];let entity=id;if(id)await run(db,'UPDATE shipping_rates SET name=?,region=?,province=?,city=?,rate=?,active=?,cod_allowed=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',...args,id);else entity=(await run(db,'INSERT INTO shipping_rates (name,region,province,city,rate,active,cod_allowed) VALUES (?,?,?,?,?,?,?)',...args)).meta.last_row_id;await audit(s,'SHIPPING_RATE_UPDATED','shipping',entity,{rate});return json({ok:true})}
 const reseller=path.match(/^\/api\/admin\/resellers\/(\d+)$/);if(reseller&&req.method==='PUT'){const b=await parse(req);if(!['New','Contacted','Closed'].includes(b.status))fail('Invalid inquiry status.');await run(db,'UPDATE reseller_inquiries SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?',b.status,Number(reseller[1]));await audit(s,'RESELLER_INQUIRY_UPDATED','reseller',reseller[1]);return json({ok:true})}
 return null;
}
