-- PostgreSQL production schema. Prices and fees are integer centavos.
CREATE TABLE "admins" (
 "id" INTEGER PRIMARY KEY,
 "username" TEXT NOT NULL,
 "password_hash" TEXT NOT NULL,
 "must_change" INTEGER DEFAULT 1 NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 UNIQUE ("username")
);
CREATE TABLE "contact_messages" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" TEXT NOT NULL,
 "email" TEXT NOT NULL,
 "mobile" TEXT NOT NULL,
 "subject" TEXT NOT NULL,
 "message" TEXT NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
CREATE TABLE "customers" (
 "id" TEXT PRIMARY KEY,
 "name" TEXT NOT NULL,
 "mobile" TEXT NOT NULL,
 "email" TEXT,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
CREATE TABLE "inventory_movements" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "product_id" INTEGER NOT NULL,
 "delta" INTEGER NOT NULL,
 "reason" TEXT NOT NULL,
 "order_id" INTEGER,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
CREATE TABLE "rate_limits" (
 "key" TEXT PRIMARY KEY,
 "count" INTEGER NOT NULL,
 "expires" BIGINT NOT NULL
);
CREATE TABLE "order_items" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "order_id" INTEGER NOT NULL,
 "product_id" INTEGER NOT NULL,
 "name" TEXT NOT NULL,
 "size" TEXT NOT NULL,
 "image" TEXT NOT NULL,
 "unit_price" INTEGER NOT NULL,
 "quantity" INTEGER NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 CONSTRAINT quantity_positive CHECK(quantity>0)
);
CREATE TABLE "orders" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "number" TEXT NOT NULL,
 "customer_id" TEXT NOT NULL,
 "address" TEXT NOT NULL,
 "barangay" TEXT NOT NULL,
 "city" TEXT NOT NULL,
 "province" TEXT NOT NULL,
 "postal" TEXT NOT NULL,
 "delivery_method" TEXT NOT NULL,
 "subtotal" INTEGER NOT NULL,
 "delivery_fee" INTEGER NOT NULL,
 "total" INTEGER NOT NULL,
 "status" TEXT NOT NULL,
 "notes" TEXT DEFAULT '' NOT NULL,
 "tracking_hash" TEXT NOT NULL,
 "idempotency_key" TEXT NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "region" TEXT DEFAULT '' NOT NULL,
 "shipping_zone" TEXT DEFAULT '' NOT NULL,
 "courier" TEXT DEFAULT '' NOT NULL,
 "tracking_number" TEXT DEFAULT '' NOT NULL,
 UNIQUE ("idempotency_key"),
 UNIQUE ("number")
);
CREATE TABLE "payments" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "order_id" INTEGER NOT NULL,
 "method" TEXT NOT NULL,
 "status" TEXT NOT NULL,
 "proof_id" TEXT,
 "reason" TEXT DEFAULT '' NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 UNIQUE ("order_id")
);
CREATE TABLE "product_images" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "product_id" INTEGER NOT NULL,
 "url" TEXT NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
CREATE TABLE "products" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" TEXT NOT NULL,
 "slug" TEXT NOT NULL,
 "size" TEXT NOT NULL,
 "price" INTEGER NOT NULL,
 "stock" INTEGER DEFAULT 0 NOT NULL,
 "description" TEXT NOT NULL,
 "short_description" TEXT NOT NULL,
 "image" TEXT NOT NULL,
 "sku" TEXT NOT NULL,
 "active" INTEGER DEFAULT 1 NOT NULL,
 "featured" INTEGER DEFAULT 0 NOT NULL,
 "deleted" INTEGER DEFAULT 0 NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 UNIQUE ("sku"),
 UNIQUE ("slug"),
 CONSTRAINT stock_nonnegative CHECK(stock>=0),
 CONSTRAINT price_nonnegative CHECK(price>=0)
);
CREATE TABLE "sessions" (
 "token_hash" TEXT PRIMARY KEY,
 "admin_id" INTEGER NOT NULL,
 "csrf" TEXT NOT NULL,
 "expires" BIGINT NOT NULL
);
CREATE TABLE "store_settings" (
 "key" TEXT PRIMARY KEY,
 "value" TEXT NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
CREATE TABLE "uploads" (
 "id" TEXT PRIMARY KEY,
 "kind" TEXT NOT NULL,
 "mime" TEXT NOT NULL,
 "size" INTEGER NOT NULL,
 "claim_hash" TEXT,
 "claimed" INTEGER DEFAULT 0 NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
CREATE TABLE "shipping_rates" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" TEXT NOT NULL,
 "region" TEXT DEFAULT '' NOT NULL,
 "province" TEXT DEFAULT '' NOT NULL,
 "city" TEXT DEFAULT '' NOT NULL,
 "rate" INTEGER NOT NULL,
 "active" INTEGER DEFAULT 1 NOT NULL,
 "cod_allowed" INTEGER DEFAULT 1 NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 CHECK(rate>=0)
);
CREATE TABLE "reseller_inquiries" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "name" TEXT NOT NULL,
 "email" TEXT NOT NULL,
 "mobile" TEXT NOT NULL,
 "location" TEXT NOT NULL,
 "facebook" TEXT DEFAULT '' NOT NULL,
 "message" TEXT NOT NULL,
 "status" TEXT DEFAULT 'New' NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL,
 "updated_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
CREATE TABLE "audit_logs" (
 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 "admin_id" INTEGER,
 "action" TEXT NOT NULL,
 "entity_type" TEXT NOT NULL,
 "entity_id" TEXT NOT NULL,
 "metadata" TEXT DEFAULT '{}' NOT NULL,
 "created_at" TEXT DEFAULT to_char(timezone('UTC',now()), 'YYYY-MM-DD HH24:MI:SS') NOT NULL
);
ALTER TABLE "inventory_movements" ADD CONSTRAINT "fk_inventory_movements_1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION;
ALTER TABLE "inventory_movements" ADD CONSTRAINT "fk_inventory_movements_2" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION;
ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_3" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION;
ALTER TABLE "order_items" ADD CONSTRAINT "fk_order_items_4" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION;
ALTER TABLE "orders" ADD CONSTRAINT "fk_orders_5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION;
ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_6" FOREIGN KEY ("proof_id") REFERENCES "uploads"("id") ON DELETE NO ACTION;
ALTER TABLE "payments" ADD CONSTRAINT "fk_payments_7" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE NO ACTION;
ALTER TABLE "product_images" ADD CONSTRAINT "fk_product_images_8" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE;
ALTER TABLE "sessions" ADD CONSTRAINT "fk_sessions_9" FOREIGN KEY ("admin_id") REFERENCES "admins"("id") ON DELETE CASCADE;
ALTER TABLE "audit_logs" ADD CONSTRAINT "fk_audit_logs_10" FOREIGN KEY ("admin_id") REFERENCES "admins"("id") ON DELETE NO ACTION;

CREATE OR REPLACE FUNCTION reserve_stock_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 UPDATE products SET stock=stock-NEW.quantity,updated_at=to_char(timezone('UTC',now()),'YYYY-MM-DD HH24:MI:SS') WHERE id=NEW.product_id AND active=1 AND deleted=0 AND stock>=NEW.quantity;
 IF NOT FOUND THEN RAISE EXCEPTION 'stock unavailable or product inactive'; END IF;
 INSERT INTO inventory_movements(product_id,delta,reason,order_id) VALUES(NEW.product_id,-NEW.quantity,'Order reserved',NEW.order_id);
 RETURN NEW;
END $$;
CREATE TRIGGER reserve_stock BEFORE INSERT ON order_items FOR EACH ROW EXECUTE FUNCTION reserve_stock_fn();
CREATE OR REPLACE FUNCTION restore_cancelled_stock_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NEW.status='Cancelled' AND OLD.status<>'Cancelled' THEN
  UPDATE products p SET stock=p.stock+i.quantity,updated_at=to_char(timezone('UTC',now()),'YYYY-MM-DD HH24:MI:SS') FROM (SELECT product_id,SUM(quantity)::integer quantity FROM order_items WHERE order_id=NEW.id GROUP BY product_id) i WHERE p.id=i.product_id;
  INSERT INTO inventory_movements(product_id,delta,reason,order_id) SELECT product_id,quantity,'Cancelled order restored',NEW.id FROM order_items WHERE order_id=NEW.id;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER restore_cancelled_stock AFTER UPDATE OF status ON orders FOR EACH ROW EXECUTE FUNCTION restore_cancelled_stock_fn();
CREATE OR REPLACE FUNCTION final_order_status_fn() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF OLD.status IN ('Cancelled','Completed') AND NEW.status<>OLD.status THEN RAISE EXCEPTION 'Final order status cannot change'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER final_order_status BEFORE UPDATE OF status ON orders FOR EACH ROW EXECUTE FUNCTION final_order_status_fn();
CREATE UNIQUE INDEX payments_proof_unique ON payments(proof_id) WHERE proof_id IS NOT NULL;

CREATE INDEX idx_orders_status_date ON orders(status,created_at);
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_items_order ON order_items(order_id);
CREATE INDEX idx_inventory_product ON inventory_movements(product_id,created_at);
CREATE INDEX idx_sessions_expiry ON sessions(expires);
CREATE INDEX idx_limits_expiry ON rate_limits(expires);
CREATE INDEX idx_products_active ON products(deleted,active);
CREATE INDEX idx_product_images_product ON product_images(product_id);

CREATE INDEX idx_shipping_location ON shipping_rates(active,province,city);
CREATE INDEX idx_resellers_status ON reseller_inquiries(status,created_at);
CREATE INDEX idx_audit_date ON audit_logs(created_at);
