import {imageUrl} from './images';
import React,{useState,useEffect,useRef,useId} from 'react';
import {Link,NavLink,useNavigate,useLocation} from 'react-router-dom';
import {ShoppingBag,Search,Menu,X,Plus,Minus,Phone,MapPin,Package,Flame,Heart,UtensilsCrossed,Facebook} from 'lucide-react';
import {useStore,peso} from './store';
export function FacebookIcon({size=18}){return <Facebook size={size} aria-hidden="true" fill="currentColor" strokeWidth={0}/>;}
export function Brand(){const{settings}=useStore();return <Link className="brand" to="/"><img src={settings?.logo&&settings.logo!=='/assets/brand.png'?settings.logo:'/assets/brand-small.webp'} alt="BEL logo"/><span>BEL<small>HOME MADE CHILI GARLIC</small></span></Link>}
export function Header(){const {cart,settings}=useStore(),[menu,setMenu]=useState(false),[search,setSearch]=useState(false),[query,setQuery]=useState('');const nav=useNavigate(),loc=useLocation();useEffect(()=>{setMenu(false);setSearch(false);window.scrollTo(0,0)},[loc.pathname]);return <>{settings?.announcement_enabled&&<div className="announcement">{settings.announcement}</div>}<header className="header"><Brand/><nav id="store-navigation" className={menu?'mobile-open':''} aria-label="Main navigation"><NavLink to="/" end>Home</NavLink><NavLink to="/shop">Shop</NavLink><NavLink to="/about">Our story</NavLink><NavLink to="/contact">Contact</NavLink><NavLink to="/reseller">Reseller</NavLink><NavLink className="nav-track-link" to="/track"><Package size={16} aria-hidden="true"/>Track Order</NavLink></nav><div className="header-actions"><button className="icon-button" aria-label="Search products" aria-expanded={search} aria-controls="store-search" onClick={()=>setSearch(!search)}><Search size={21} aria-hidden="true"/><span className="control-label">Search</span></button><Link className="bag-link" to="/cart" aria-label={'Shopping bag, '+cart.reduce((s,i)=>s+i.quantity,0)+' items'}><ShoppingBag size={21} aria-hidden="true"/><span className="control-label">Bag</span><span className="bag-count">{cart.reduce((s,i)=>s+i.quantity,0)}</span></Link><button className="icon-button mobile-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="store-navigation" aria-label={menu?"Close menu":"Open menu"}>{menu?<X aria-hidden="true"/>:<Menu aria-hidden="true"/>}<span className="control-label">{menu?"Close":"Menu"}</span></button></div><NavLink className="mobile-track-link" to="/track"><Package size={17} aria-hidden="true"/>Track your order</NavLink>{search&&<form id="store-search" className="header-search" onSubmit={e=>{e.preventDefault();nav('/shop?q='+encodeURIComponent(query));setSearch(false)}}><input autoFocus aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search chili garlic jars"/><button className="button">Search</button></form>}</header></>}
export function Footer(){const{settings:s}=useStore();if(!s)return null;return <footer><div className="footer-grid"><div><Brand/><p>Homemade comfort.<br/>A little extra heat.</p></div><div><h4>Explore BEL</h4><Link to="/shop">Shop all jars</Link><Link to="/about">Our story</Link><Link to="/faq">FAQs</Link><Link to="/reseller">Become a reseller</Link><Link to="/track">Track your order</Link></div><div><h4>Say hello</h4><a href={'tel:+63'+s.phone.slice(1)}>{s.phone}</a><Link to="/contact">Contact us</Link><p>{s.address}</p></div><div><h4>From our kitchen</h4><p>Made in Lubao, Pampanga.<br/>{s.tagline}</p>{['facebook','instagram','tiktok'].filter(k=>s[k]).map(k=><a key={k} href={s[k]} target="_blank" rel="noopener noreferrer" className="social-footer-link">{k==='facebook'&&<FacebookIcon size={17}/>}<span>{k[0].toUpperCase()+k.slice(1)}</span></a>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {s.business_name}</span><span>Made with care. Shared with love.</span></div><div className="footer-admin"><Link to="/admin">Admin Login</Link></div></footer>}
export function Quantity({value,onChange,max=999,label='Quantity'}){return <div className="quantity"><button type="button" aria-label={'Decrease '+label} disabled={value<=1} onClick={()=>onChange(value-1)}><Minus size={14}/></button><span aria-live="polite">{value}</span><button type="button" aria-label={'Increase '+label} disabled={value>=max} onClick={()=>onChange(value+1)}><Plus size={14}/></button></div>}
export function Stock({stock,active=true}){return <span className={'stock '+(!stock||!active?'out':'')}>{!active?'Unavailable':stock===0?'Out of stock':stock<=5?'Only '+stock+' left':'In stock'}</span>}
export function ProductCard({product:p}){const{add}=useStore(),[q,setQ]=useState(1);return <article className="product-card"><Link to={'/product/'+p.slug} className="product-image"><span className="product-size">{p.size} jar</span><img src={imageUrl(p.image)} loading="lazy" alt={p.name+' — '+p.size}/></Link><div className="product-card-content"><div className="product-title"><h3><Link to={'/product/'+p.slug}>{p.name}</Link></h3><strong>{peso(p.price)}</strong></div><p>{p.short_description}</p><div className="card-stock"><span>{p.size} · Homemade chili garlic</span><Stock stock={p.stock}/></div><div className="card-actions"><Quantity value={q} max={p.stock} onChange={setQ}/><button className="button" disabled={!p.stock} onClick={()=>add(p,q)}><ShoppingBag size={16}/>Add to bag</button></div><Link className="text-link" to={'/product/'+p.slug}>View product</Link></div></article>}
export function Perks(){return <div className="perks">{[[Heart,'Homemade goodness','Prepared with care, from our kitchen to your table.'],[Flame,'Flavor-packed','Crispy garlic, bold chili, and aromatic oil.'],[UtensilsCrossed,'Perfect with everything','Your everyday favorites, with a little extra kick.'],[Package,'A kick in every bite','Savory garlic meets satisfying spicy heat.']].map(([Icon,title,copy])=><div key={title}><Icon size={27}/><h3>{title}</h3><p>{copy}</p></div>)}</div>}
export function ErrorBox({children}){return children?<div className="error" role="alert">{children}</div>:null}
export function Empty({title,copy,to='/shop',label='Explore the shop'}){return <div className="empty"><ShoppingBag size={38}/><h2>{title}</h2><p>{copy}</p><Link className="button" to={to}>{label}</Link></div>}
export function Field({label,textarea=false,children,...props}){return <label className="field"><span>{label}{props.required&&' *'}</span>{children||(textarea?<textarea rows="4" {...props}/>:<input {...props}/>)}</label>}
export function Modal({title,children,onClose}){const ref=useRef(),titleId=useId();useEffect(()=>{ref.current.showModal()},[]);return <dialog className="modal" aria-labelledby={titleId} ref={ref} onCancel={onClose}><div className="modal-heading"><h2 id={titleId}>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X aria-hidden="true"/><span className="control-label">Close</span></button></div>{children}</dialog>}
export const pairings=['Fried rice','Siomai','Dumplings','Noodles','Fried chicken','Silog meals','Eggs','Pizza','Street food'];


// Keep real table headers on desktop and repeat their labels on phone cards.
export function ResponsiveTable({children,...props}) {
 const sections=React.Children.toArray(children);
 const head=sections.find(section=>section.type==='thead');
 const headerRow=head&&React.Children.toArray(head.props.children)[0];
 const labels=headerRow?React.Children.toArray(headerRow.props.children).map(cell=>cell.props.children||'Actions'):[];
 return <table {...props} className={'responsive-table '+(props.className||'')} role="table">{sections.map(section=>{
  if(section.type==='thead')return React.cloneElement(section,{role:'rowgroup'},React.Children.map(section.props.children,row=>React.cloneElement(row,{role:'row'},React.Children.map(row.props.children,cell=>React.cloneElement(cell,{role:'columnheader'})))));
  if(section.type!=='tbody')return section;
  return React.cloneElement(section,{role:'rowgroup'},React.Children.map(section.props.children,row=>React.isValidElement(row)?React.cloneElement(row,{role:'row'},React.Children.map(row.props.children,(cell,index)=>React.isValidElement(cell)?React.cloneElement(cell,{'data-label':labels[index]||'Actions',role:'cell'}):cell)):row));
 })}</table>;
}
