import React,{useEffect} from 'react';
import {BrowserRouter,HashRouter,Routes,Route,useLocation} from 'react-router-dom';
import {StoreProvider,useStore} from './store';
import {Header,Footer,ErrorBox} from './components';
import {Home,Shop,Product,Cart,Track,About,Contact,FAQ,NotFound} from './pages';
import {Admin} from './admin';
import {RevisedCheckout as Checkout,OrderTicket as Confirmation,Reseller} from './customer-extras';
function PreviewUnavailable(){return <section className="section page"><h1 className="page-title">Design preview only</h1><p>Checkout, payments and order tracking need the full website server. No orders are accepted here.</p></section>}
const pagesPreview=process.env.NEXT_PUBLIC_PAGES_PREVIEW==='true';
const Router=pagesPreview?HashRouter:BrowserRouter;
function App(){const{data,error,refresh,products,add}=useStore(),loc=useLocation();useEffect(()=>{const ctx=document.modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:'bel_list_products',title:'List BEL jars',description:'Read the currently available BEL products, prices, and stock.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>({products:products?.map(({id,name,size,price,stock})=>({id,name,size,price,stock}))||[]})});register({name:'bel_add_to_bag',title:'Add a BEL jar to the bag',description:'Stage a product in the local shopping bag. This does not place or pay for an order.',inputSchema:{type:'object',properties:{id:{type:'integer'},quantity:{type:'integer',minimum:1}},required:['id','quantity'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async b=>{if(!Number.isInteger(b.id)||!Number.isInteger(b.quantity)||b.quantity<1)throw Error('Invalid product or quantity.');const p=products?.find(p=>p.id===b.id);if(!p||!add(p,b.quantity))throw Error('Product or quantity unavailable.');return{added:true,id:p.id,quantity:b.quantity}}});return()=>lifecycle.abort()},[products,add]);if(loc.pathname.startsWith('/admin'))return <Admin/>;return <><a className="skip-link" href="#main">Skip to content</a><Header/><main id="main">{error?<div className="section"><ErrorBox>{error}</ErrorBox><button className="button" onClick={refresh}>Try again</button></div>:!data?<div className="loading" role="status"><span/>Preparing a little goodness…</div>:<Routes><Route path="/" element={<Home/>}/><Route path="/shop" element={<Shop/>}/><Route path="/product/:slug" element={<Product/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={pagesPreview?<PreviewUnavailable/>:<Checkout/>}/><Route path="/confirmation/:number" element={pagesPreview?<PreviewUnavailable/>:<Confirmation/>}/><Route path="/track" element={pagesPreview?<PreviewUnavailable/>:<Track/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/reseller" element={<Reseller/>}/><Route path="/faq" element={<FAQ/>}/><Route path="*" element={<NotFound/>}/></Routes>}</main><Footer/></>}
export default function Storefront(){return <Router><StoreProvider><App/></StoreProvider></Router>}

