import {previewApi} from '../pages/api.mjs';
import React,{createContext,useContext,useState,useEffect,useCallback} from 'react';
export let csrf='';export const setCsrf=t=>{csrf=t||''};
export async function api(path,options={}){if(process.env.NEXT_PUBLIC_PAGES_PREVIEW==='true')return previewApi(path,options);const r=await fetch('/api'+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),'X-CSRF-Token':csrf,...options.headers},body:options.body instanceof FormData?options.body:options.body===undefined?undefined:JSON.stringify(options.body)});const data=await r.json();if(!r.ok){if(r.status===401&&path.startsWith('/admin/')&&path!=='/admin/login')window.dispatchEvent(new Event('bel-admin-expired'));const e=new Error(data.error||'Something went wrong. Please try again.');e.status=r.status;throw e}return data}
export const peso=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:2,minimumFractionDigits:0}).format(n);
export const cents=n=>peso(n/100);
const Context=createContext();export const useStore=()=>useContext(Context);
export function StoreProvider({children}){const [data,setData]=useState(null),[error,setError]=useState(''),[toast,setToast]=useState('');const [cart,setCart]=useState(()=>{try{const x=JSON.parse(localStorage.getItem('bel-bag')||'[]');return Array.isArray(x)?x.filter(i=>Number.isInteger(i.id)&&Number.isInteger(i.quantity)&&i.quantity>0):[]}catch{return[]}});
 const refresh=useCallback(async()=>{try{const d=await api('/store');setData(d);setError('');return d}catch(e){setError(e.message)}},[]);useEffect(()=>{refresh()},[refresh]);useEffect(()=>{localStorage.setItem('bel-bag',JSON.stringify(cart))},[cart]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t)}},[toast]);
 function add(p,quantity=1){const current=cart.find(i=>i.id===p.id)?.quantity||0;if(quantity<1||!Number.isInteger(quantity)||current+quantity>p.stock){setToast('Only '+p.stock+' jars available.');return false}setCart(v=>v.some(i=>i.id===p.id)?v.map(i=>i.id===p.id?{...i,quantity:i.quantity+quantity}:i):[...v,{id:p.id,quantity}]);setToast('Added to your bag!');return true}
 const change=(id,q)=>{const p=data?.products.find(p=>p.id===id);if(q<1)return setCart(v=>v.filter(i=>i.id!==id));if(!p||q>p.stock)return setToast('Not enough stock available.');setCart(v=>v.map(i=>i.id===id?{...i,quantity:q}:i))};
 return <Context.Provider value={{...data,data,error,refresh,cart,setCart,add,change,notify:setToast}}>{children}{toast&&<div className="toast" role="status">{toast}</div>}</Context.Provider>}
export function useAction(){const[busy,setBusy]=useState(false),[error,setError]=useState('');return{busy,error,clear:()=>setError(''),run:async action=>{setBusy(true);setError('');try{return await action()}catch(e){setError(e.message)}finally{setBusy(false)}}}}
